# App
server.port=8080
spring.application.name=demo

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ev_rental;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true

security.jwt.secret=YqYw2Xg1O7n3lV1V2zj1I6oGqv8oXJ9hJH0f8FXyjlzQGm6Cq7qf8V0PZ1cM7QZgQmJz0Q4u2bVq+G7Y9Q==
security.jwt.expiration-ms=86400000

# ===== PayOS =====
payos.client-id=7fe322bc-de18-4984-a775-02df67d8a3a1
payos.api-key=81c83538-c742-43f6-b3b0-76c7f4278fb1
payos.checksum-key=d6fcdeb407370508ccd4275288055e18b55b51fa8ee5b5a6234249b38f727740

# ===== App URLs =====
app.frontend.base-url=http://localhost:3000

# ===== PayOS redirect paths =====
app.payment.success-path=/payment/success
app.payment.cancel-path=/payment/cancel

# ===== File Upload =====
app.upload.dir=uploads
app.upload.max-file-size=10MB
app.upload.max-request-size=10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===== AI API =====
#Inbox Khôi ?? nh?n
gemini.api.key=AIzaSyAPE6GSZPfPkUBtrDt-ue63T70CzofwDlY