# App
server.port=8080
spring.application.name=demo

# SQL Server (local)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CarRentalDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234567890
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

security.jwt.secret=YqYw2Xg1O7n3lV1V2zj1I6oGqv8oXJ9hJH0f8FXyjlzQGm6Cq7qf8V0PZ1cM7QZgQmJz0Q4u2bVq+G7Y9Q==
security.jwt.expiration-ms=86400000